# Experiment configurations
core_counts: [4, 8, 16, 32]
task_counts: [10, 50, 100, 200, 400, 600]
utilizations: [0.25, 0.5, 0.75]
policies: ['FIFO', 'LDF', 'HEFT']
allocation_policies: ['FFD', 'BFD', 'WFD', 'RR']
sim_time: 5000
